//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOffersDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public OFERTA()
        {
            this.VALORACION = new HashSet<VALORACION>();
        }
    
        public decimal ID_OFERTA { get; set; }
        public decimal CANTIDAD_MINIMA { get; set; }
        public decimal CANTIDAD_MAXIMA { get; set; }
        public decimal PRECIO_NORMAL { get; set; }
        public decimal PRECIO_OFERTA { get; set; }
        public string IMAGEN { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal CAMPANA_FK { get; set; }
        public decimal PRODUCTO_FK { get; set; }
    
        public virtual CAMPANA CAMPANA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
    }
}
