//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOffersDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_USUARIO
    {
        public ROL_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_ROL_USUARIO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
