//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOffers.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAMPANA> CAMPANA { get; set; }
        public DbSet<CUPON> CUPON { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<MAILLIST> MAILLIST { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PUNTOS> PUNTOS { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<TRAMO> TRAMO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
    
        public virtual int DELETECAMPANA(Nullable<decimal> p_ID_CAMPANA)
        {
            var p_ID_CAMPANAParameter = p_ID_CAMPANA.HasValue ?
                new ObjectParameter("P_ID_CAMPANA", p_ID_CAMPANA) :
                new ObjectParameter("P_ID_CAMPANA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETECAMPANA", p_ID_CAMPANAParameter);
        }
    
        public virtual int DELETECUPON(Nullable<decimal> p_ID_CUPON)
        {
            var p_ID_CUPONParameter = p_ID_CUPON.HasValue ?
                new ObjectParameter("P_ID_CUPON", p_ID_CUPON) :
                new ObjectParameter("P_ID_CUPON", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETECUPON", p_ID_CUPONParameter);
        }
    
        public virtual int DELETEEMPRESA(Nullable<decimal> p_ID_EMPRESA)
        {
            var p_ID_EMPRESAParameter = p_ID_EMPRESA.HasValue ?
                new ObjectParameter("P_ID_EMPRESA", p_ID_EMPRESA) :
                new ObjectParameter("P_ID_EMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEEMPRESA", p_ID_EMPRESAParameter);
        }
    
        public virtual int DELETEMAILLIST(Nullable<decimal> p_ID_MAILLIST)
        {
            var p_ID_MAILLISTParameter = p_ID_MAILLIST.HasValue ?
                new ObjectParameter("P_ID_MAILLIST", p_ID_MAILLIST) :
                new ObjectParameter("P_ID_MAILLIST", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMAILLIST", p_ID_MAILLISTParameter);
        }
    
        public virtual int DELETEOFERTA(Nullable<decimal> p_ID_OFERTA)
        {
            var p_ID_OFERTAParameter = p_ID_OFERTA.HasValue ?
                new ObjectParameter("P_ID_OFERTA", p_ID_OFERTA) :
                new ObjectParameter("P_ID_OFERTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEOFERTA", p_ID_OFERTAParameter);
        }
    
        public virtual int DELETEPRODUCTO(Nullable<decimal> p_ID_PRODUCTO)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEPRODUCTO", p_ID_PRODUCTOParameter);
        }
    
        public virtual int DELETEPUNTOS(Nullable<decimal> p_ID_PUNTOS)
        {
            var p_ID_PUNTOSParameter = p_ID_PUNTOS.HasValue ?
                new ObjectParameter("P_ID_PUNTOS", p_ID_PUNTOS) :
                new ObjectParameter("P_ID_PUNTOS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEPUNTOS", p_ID_PUNTOSParameter);
        }
    
        public virtual int DELETEROLUSUARIO(Nullable<decimal> p_ID_ROL_USUARIO)
        {
            var p_ID_ROL_USUARIOParameter = p_ID_ROL_USUARIO.HasValue ?
                new ObjectParameter("P_ID_ROL_USUARIO", p_ID_ROL_USUARIO) :
                new ObjectParameter("P_ID_ROL_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEROLUSUARIO", p_ID_ROL_USUARIOParameter);
        }
    
        public virtual int DELETERUBRO(Nullable<decimal> p_ID_RUBRO)
        {
            var p_ID_RUBROParameter = p_ID_RUBRO.HasValue ?
                new ObjectParameter("P_ID_RUBRO", p_ID_RUBRO) :
                new ObjectParameter("P_ID_RUBRO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETERUBRO", p_ID_RUBROParameter);
        }
    
        public virtual int DELETETIENDA(Nullable<decimal> p_ID_TIENDA)
        {
            var p_ID_TIENDAParameter = p_ID_TIENDA.HasValue ?
                new ObjectParameter("P_ID_TIENDA", p_ID_TIENDA) :
                new ObjectParameter("P_ID_TIENDA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETETIENDA", p_ID_TIENDAParameter);
        }
    
        public virtual int DELETETRAMO(Nullable<decimal> p_ID_TRAMO)
        {
            var p_ID_TRAMOParameter = p_ID_TRAMO.HasValue ?
                new ObjectParameter("P_ID_TRAMO", p_ID_TRAMO) :
                new ObjectParameter("P_ID_TRAMO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETETRAMO", p_ID_TRAMOParameter);
        }
    
        public virtual int DELETEUSUARIO(Nullable<decimal> p_ID_USUARIO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEUSUARIO", p_ID_USUARIOParameter);
        }
    
        public virtual int DELETEVALORACION(Nullable<decimal> p_ID_VALORACION)
        {
            var p_ID_VALORACIONParameter = p_ID_VALORACION.HasValue ?
                new ObjectParameter("P_ID_VALORACION", p_ID_VALORACION) :
                new ObjectParameter("P_ID_VALORACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEVALORACION", p_ID_VALORACIONParameter);
        }
    
        public virtual int ELIMINAREMPRESA(Nullable<decimal> p_ID_EMPRESA, string p_ESTADO)
        {
            var p_ID_EMPRESAParameter = p_ID_EMPRESA.HasValue ?
                new ObjectParameter("P_ID_EMPRESA", p_ID_EMPRESA) :
                new ObjectParameter("P_ID_EMPRESA", typeof(decimal));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAREMPRESA", p_ID_EMPRESAParameter, p_ESTADOParameter);
        }
    
        public virtual int ELIMINARTIENDA(Nullable<decimal> p_ID_TIENDA, string p_ESTADO)
        {
            var p_ID_TIENDAParameter = p_ID_TIENDA.HasValue ?
                new ObjectParameter("P_ID_TIENDA", p_ID_TIENDA) :
                new ObjectParameter("P_ID_TIENDA", typeof(decimal));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARTIENDA", p_ID_TIENDAParameter, p_ESTADOParameter);
        }
    
        public virtual int ELIMINARUSUARIO(Nullable<decimal> p_ID_USUARIO, string p_ESTADO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARUSUARIO", p_ID_USUARIOParameter, p_ESTADOParameter);
        }
    
        public virtual int ELIMMINARCAMPANA(Nullable<decimal> p_ID_CAMPANA, string p_ESTADO)
        {
            var p_ID_CAMPANAParameter = p_ID_CAMPANA.HasValue ?
                new ObjectParameter("P_ID_CAMPANA", p_ID_CAMPANA) :
                new ObjectParameter("P_ID_CAMPANA", typeof(decimal));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMMINARCAMPANA", p_ID_CAMPANAParameter, p_ESTADOParameter);
        }
    
        public virtual int INSERTCAMPANA(string p_NOMBRE_CAMPANA, string p_DESCRIPCION, Nullable<System.DateTime> p_FECHA_INICIO, Nullable<System.DateTime> p_FECHA_FIN, Nullable<System.DateTime> p_FECHA, string p_ESTADO, Nullable<decimal> p_USUARIO_FK)
        {
            var p_NOMBRE_CAMPANAParameter = p_NOMBRE_CAMPANA != null ?
                new ObjectParameter("P_NOMBRE_CAMPANA", p_NOMBRE_CAMPANA) :
                new ObjectParameter("P_NOMBRE_CAMPANA", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_FECHA_INICIOParameter = p_FECHA_INICIO.HasValue ?
                new ObjectParameter("P_FECHA_INICIO", p_FECHA_INICIO) :
                new ObjectParameter("P_FECHA_INICIO", typeof(System.DateTime));
    
            var p_FECHA_FINParameter = p_FECHA_FIN.HasValue ?
                new ObjectParameter("P_FECHA_FIN", p_FECHA_FIN) :
                new ObjectParameter("P_FECHA_FIN", typeof(System.DateTime));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCAMPANA", p_NOMBRE_CAMPANAParameter, p_DESCRIPCIONParameter, p_FECHA_INICIOParameter, p_FECHA_FINParameter, p_FECHAParameter, p_ESTADOParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int INSERTCUPON(string p_PDF, Nullable<decimal> p_TOPE_MAXIMO, Nullable<decimal> p_DESCUENTO, Nullable<System.DateTime> p_FECHA, Nullable<System.DateTime> p_VENCIMIENTO, string p_CONDICIONES, Nullable<decimal> p_USUARIO_FK, Nullable<decimal> p_TRAMO_FK)
        {
            var p_PDFParameter = p_PDF != null ?
                new ObjectParameter("P_PDF", p_PDF) :
                new ObjectParameter("P_PDF", typeof(string));
    
            var p_TOPE_MAXIMOParameter = p_TOPE_MAXIMO.HasValue ?
                new ObjectParameter("P_TOPE_MAXIMO", p_TOPE_MAXIMO) :
                new ObjectParameter("P_TOPE_MAXIMO", typeof(decimal));
    
            var p_DESCUENTOParameter = p_DESCUENTO.HasValue ?
                new ObjectParameter("P_DESCUENTO", p_DESCUENTO) :
                new ObjectParameter("P_DESCUENTO", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_VENCIMIENTOParameter = p_VENCIMIENTO.HasValue ?
                new ObjectParameter("P_VENCIMIENTO", p_VENCIMIENTO) :
                new ObjectParameter("P_VENCIMIENTO", typeof(System.DateTime));
    
            var p_CONDICIONESParameter = p_CONDICIONES != null ?
                new ObjectParameter("P_CONDICIONES", p_CONDICIONES) :
                new ObjectParameter("P_CONDICIONES", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            var p_TRAMO_FKParameter = p_TRAMO_FK.HasValue ?
                new ObjectParameter("P_TRAMO_FK", p_TRAMO_FK) :
                new ObjectParameter("P_TRAMO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCUPON", p_PDFParameter, p_TOPE_MAXIMOParameter, p_DESCUENTOParameter, p_FECHAParameter, p_VENCIMIENTOParameter, p_CONDICIONESParameter, p_USUARIO_FKParameter, p_TRAMO_FKParameter);
        }
    
        public virtual int INSERTEMPRESA(string p_NOMBRE_EMPRESA, string p_RAZON_SOCIAL, string p_ESTADO, string p_RUT)
        {
            var p_NOMBRE_EMPRESAParameter = p_NOMBRE_EMPRESA != null ?
                new ObjectParameter("P_NOMBRE_EMPRESA", p_NOMBRE_EMPRESA) :
                new ObjectParameter("P_NOMBRE_EMPRESA", typeof(string));
    
            var p_RAZON_SOCIALParameter = p_RAZON_SOCIAL != null ?
                new ObjectParameter("P_RAZON_SOCIAL", p_RAZON_SOCIAL) :
                new ObjectParameter("P_RAZON_SOCIAL", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTEMPRESA", p_NOMBRE_EMPRESAParameter, p_RAZON_SOCIALParameter, p_ESTADOParameter, p_RUTParameter);
        }
    
        public virtual int INSERTMAILLIST(Nullable<decimal> p_ID_MAILLIST, string p_SUSCRITO, Nullable<decimal> p_USUARIO_FK)
        {
            var p_ID_MAILLISTParameter = p_ID_MAILLIST.HasValue ?
                new ObjectParameter("P_ID_MAILLIST", p_ID_MAILLIST) :
                new ObjectParameter("P_ID_MAILLIST", typeof(decimal));
    
            var p_SUSCRITOParameter = p_SUSCRITO != null ?
                new ObjectParameter("P_SUSCRITO", p_SUSCRITO) :
                new ObjectParameter("P_SUSCRITO", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMAILLIST", p_ID_MAILLISTParameter, p_SUSCRITOParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int INSERTOFERTA(Nullable<decimal> p_CANTIDAD_MINIMA, Nullable<decimal> p_CANTIDAD_MAXIMA, Nullable<decimal> p_PRECIO_NORMAL, Nullable<decimal> p_PRECIO_OFERTA, string p_IMAGEN, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_CAMPANA_FK, Nullable<decimal> p_PRODUCTO_FK)
        {
            var p_CANTIDAD_MINIMAParameter = p_CANTIDAD_MINIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MINIMA", p_CANTIDAD_MINIMA) :
                new ObjectParameter("P_CANTIDAD_MINIMA", typeof(decimal));
    
            var p_CANTIDAD_MAXIMAParameter = p_CANTIDAD_MAXIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MAXIMA", p_CANTIDAD_MAXIMA) :
                new ObjectParameter("P_CANTIDAD_MAXIMA", typeof(decimal));
    
            var p_PRECIO_NORMALParameter = p_PRECIO_NORMAL.HasValue ?
                new ObjectParameter("P_PRECIO_NORMAL", p_PRECIO_NORMAL) :
                new ObjectParameter("P_PRECIO_NORMAL", typeof(decimal));
    
            var p_PRECIO_OFERTAParameter = p_PRECIO_OFERTA.HasValue ?
                new ObjectParameter("P_PRECIO_OFERTA", p_PRECIO_OFERTA) :
                new ObjectParameter("P_PRECIO_OFERTA", typeof(decimal));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_CAMPANA_FKParameter = p_CAMPANA_FK.HasValue ?
                new ObjectParameter("P_CAMPANA_FK", p_CAMPANA_FK) :
                new ObjectParameter("P_CAMPANA_FK", typeof(decimal));
    
            var p_PRODUCTO_FKParameter = p_PRODUCTO_FK.HasValue ?
                new ObjectParameter("P_PRODUCTO_FK", p_PRODUCTO_FK) :
                new ObjectParameter("P_PRODUCTO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTOFERTA", p_CANTIDAD_MINIMAParameter, p_CANTIDAD_MAXIMAParameter, p_PRECIO_NORMALParameter, p_PRECIO_OFERTAParameter, p_IMAGENParameter, p_FECHAParameter, p_CAMPANA_FKParameter, p_PRODUCTO_FKParameter);
        }
    
        public virtual int INSERTPRODUCTO(string p_NOMBRE_PRODUCTO, string p_DESCRIPCION, string p_COLOR, string p_PERECIBLE, string p_MARCA, Nullable<decimal> p_RUBRO_FK)
        {
            var p_NOMBRE_PRODUCTOParameter = p_NOMBRE_PRODUCTO != null ?
                new ObjectParameter("P_NOMBRE_PRODUCTO", p_NOMBRE_PRODUCTO) :
                new ObjectParameter("P_NOMBRE_PRODUCTO", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_COLORParameter = p_COLOR != null ?
                new ObjectParameter("P_COLOR", p_COLOR) :
                new ObjectParameter("P_COLOR", typeof(string));
    
            var p_PERECIBLEParameter = p_PERECIBLE != null ?
                new ObjectParameter("P_PERECIBLE", p_PERECIBLE) :
                new ObjectParameter("P_PERECIBLE", typeof(string));
    
            var p_MARCAParameter = p_MARCA != null ?
                new ObjectParameter("P_MARCA", p_MARCA) :
                new ObjectParameter("P_MARCA", typeof(string));
    
            var p_RUBRO_FKParameter = p_RUBRO_FK.HasValue ?
                new ObjectParameter("P_RUBRO_FK", p_RUBRO_FK) :
                new ObjectParameter("P_RUBRO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPRODUCTO", p_NOMBRE_PRODUCTOParameter, p_DESCRIPCIONParameter, p_COLORParameter, p_PERECIBLEParameter, p_MARCAParameter, p_RUBRO_FKParameter);
        }
    
        public virtual int INSERTPUNTOS(Nullable<decimal> p_CANTIDAD, Nullable<decimal> p_USUARIO_FK)
        {
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPUNTOS", p_CANTIDADParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int INSERTROLUSUARIO(string p_NOMBRE)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTROLUSUARIO", p_NOMBREParameter);
        }
    
        public virtual int INSERTRUBRO(string p_NOMBRE_RUBRO)
        {
            var p_NOMBRE_RUBROParameter = p_NOMBRE_RUBRO != null ?
                new ObjectParameter("P_NOMBRE_RUBRO", p_NOMBRE_RUBRO) :
                new ObjectParameter("P_NOMBRE_RUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTRUBRO", p_NOMBRE_RUBROParameter);
        }
    
        public virtual int INSERTTIENDA(string p_NOMBRE_TIENDA, string p_DIRECCION, string p_ESTADO, Nullable<decimal> p_EMPRESA_FK, Nullable<decimal> p_USUARIO_FK)
        {
            var p_NOMBRE_TIENDAParameter = p_NOMBRE_TIENDA != null ?
                new ObjectParameter("P_NOMBRE_TIENDA", p_NOMBRE_TIENDA) :
                new ObjectParameter("P_NOMBRE_TIENDA", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_EMPRESA_FKParameter = p_EMPRESA_FK.HasValue ?
                new ObjectParameter("P_EMPRESA_FK", p_EMPRESA_FK) :
                new ObjectParameter("P_EMPRESA_FK", typeof(decimal));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTTIENDA", p_NOMBRE_TIENDAParameter, p_DIRECCIONParameter, p_ESTADOParameter, p_EMPRESA_FKParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int INSERTTRAMO(Nullable<decimal> p_MAXIMO, Nullable<decimal> p_MINIMO)
        {
            var p_MAXIMOParameter = p_MAXIMO.HasValue ?
                new ObjectParameter("P_MAXIMO", p_MAXIMO) :
                new ObjectParameter("P_MAXIMO", typeof(decimal));
    
            var p_MINIMOParameter = p_MINIMO.HasValue ?
                new ObjectParameter("P_MINIMO", p_MINIMO) :
                new ObjectParameter("P_MINIMO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTTRAMO", p_MAXIMOParameter, p_MINIMOParameter);
        }
    
        public virtual int INSERTUSUARIO(string p_NOMBRES_USUARIO, string p_APELLIDO_PATERNO, string p_APELLIDO_MATERNO, string p_CORREO, string p_CONTRASENA, string p_RUT, string p_ESTADO, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_ROL_USUARIO_FK)
        {
            var p_NOMBRES_USUARIOParameter = p_NOMBRES_USUARIO != null ?
                new ObjectParameter("P_NOMBRES_USUARIO", p_NOMBRES_USUARIO) :
                new ObjectParameter("P_NOMBRES_USUARIO", typeof(string));
    
            var p_APELLIDO_PATERNOParameter = p_APELLIDO_PATERNO != null ?
                new ObjectParameter("P_APELLIDO_PATERNO", p_APELLIDO_PATERNO) :
                new ObjectParameter("P_APELLIDO_PATERNO", typeof(string));
    
            var p_APELLIDO_MATERNOParameter = p_APELLIDO_MATERNO != null ?
                new ObjectParameter("P_APELLIDO_MATERNO", p_APELLIDO_MATERNO) :
                new ObjectParameter("P_APELLIDO_MATERNO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_ROL_USUARIO_FKParameter = p_ROL_USUARIO_FK.HasValue ?
                new ObjectParameter("P_ROL_USUARIO_FK", p_ROL_USUARIO_FK) :
                new ObjectParameter("P_ROL_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTUSUARIO", p_NOMBRES_USUARIOParameter, p_APELLIDO_PATERNOParameter, p_APELLIDO_MATERNOParameter, p_CORREOParameter, p_CONTRASENAParameter, p_RUTParameter, p_ESTADOParameter, p_FECHAParameter, p_ROL_USUARIO_FKParameter);
        }
    
        public virtual int INSERTVALORACION(Nullable<System.DateTime> p_FECHA, string p_IMAGEN, Nullable<decimal> p_CALIDAD, Nullable<decimal> p_ATENCION, Nullable<decimal> p_PRECIO, string p_COMENTARIO, Nullable<decimal> p_USUARIO_FK, Nullable<decimal> p_OFERTA_FK)
        {
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_CALIDADParameter = p_CALIDAD.HasValue ?
                new ObjectParameter("P_CALIDAD", p_CALIDAD) :
                new ObjectParameter("P_CALIDAD", typeof(decimal));
    
            var p_ATENCIONParameter = p_ATENCION.HasValue ?
                new ObjectParameter("P_ATENCION", p_ATENCION) :
                new ObjectParameter("P_ATENCION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_COMENTARIOParameter = p_COMENTARIO != null ?
                new ObjectParameter("P_COMENTARIO", p_COMENTARIO) :
                new ObjectParameter("P_COMENTARIO", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            var p_OFERTA_FKParameter = p_OFERTA_FK.HasValue ?
                new ObjectParameter("P_OFERTA_FK", p_OFERTA_FK) :
                new ObjectParameter("P_OFERTA_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTVALORACION", p_FECHAParameter, p_IMAGENParameter, p_CALIDADParameter, p_ATENCIONParameter, p_PRECIOParameter, p_COMENTARIOParameter, p_USUARIO_FKParameter, p_OFERTA_FKParameter);
        }
    
        public virtual int SELECTCAMPANA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTCAMPANA");
        }
    
        public virtual int SELECTCUPON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTCUPON");
        }
    
        public virtual int SELECTEMPRESA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTEMPRESA");
        }
    
        public virtual int SELECTMAILLIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTMAILLIST");
        }
    
        public virtual int SELECTOFERTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTOFERTA");
        }
    
        public virtual int SELECTPRODUCTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTPRODUCTO");
        }
    
        public virtual int SELECTPUNTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTPUNTOS");
        }
    
        public virtual int SELECTROL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTROL");
        }
    
        public virtual int SELECTROLUSUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTROLUSUARIO");
        }
    
        public virtual int SELECTRUBRO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTRUBRO");
        }
    
        public virtual int SELECTTIENDA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTTIENDA");
        }
    
        public virtual int SELECTTRAMO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTTRAMO");
        }
    
        public virtual int SELECTUSUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTUSUARIO");
        }
    
        public virtual int SELECTVALORACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SELECTVALORACION");
        }
    
        public virtual int SP_LOGIN(string p_CORREO, string p_CONTRASENA, ObjectParameter nOMBRE_ROL)
        {
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOGIN", p_CORREOParameter, p_CONTRASENAParameter, nOMBRE_ROL);
        }
    
        public virtual int UPDATECAMPANA(Nullable<decimal> p_ID_CAMPANA, string p_NOMBRE_CAMPANA, string p_DESCRIPCION, Nullable<System.DateTime> p_FECHA_INICIO, Nullable<System.DateTime> p_FECHA_FIN, Nullable<System.DateTime> p_FECHA, string p_ESTADO)
        {
            var p_ID_CAMPANAParameter = p_ID_CAMPANA.HasValue ?
                new ObjectParameter("P_ID_CAMPANA", p_ID_CAMPANA) :
                new ObjectParameter("P_ID_CAMPANA", typeof(decimal));
    
            var p_NOMBRE_CAMPANAParameter = p_NOMBRE_CAMPANA != null ?
                new ObjectParameter("P_NOMBRE_CAMPANA", p_NOMBRE_CAMPANA) :
                new ObjectParameter("P_NOMBRE_CAMPANA", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_FECHA_INICIOParameter = p_FECHA_INICIO.HasValue ?
                new ObjectParameter("P_FECHA_INICIO", p_FECHA_INICIO) :
                new ObjectParameter("P_FECHA_INICIO", typeof(System.DateTime));
    
            var p_FECHA_FINParameter = p_FECHA_FIN.HasValue ?
                new ObjectParameter("P_FECHA_FIN", p_FECHA_FIN) :
                new ObjectParameter("P_FECHA_FIN", typeof(System.DateTime));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATECAMPANA", p_ID_CAMPANAParameter, p_NOMBRE_CAMPANAParameter, p_DESCRIPCIONParameter, p_FECHA_INICIOParameter, p_FECHA_FINParameter, p_FECHAParameter, p_ESTADOParameter);
        }
    
        public virtual int UPDATECUPON(Nullable<decimal> p_ID_CUPON, string p_PDF, Nullable<decimal> p_TOPE_MAXIMO, Nullable<decimal> p_DESCUENTO, Nullable<System.DateTime> p_FECHA, Nullable<System.DateTime> p_VENCIMIENTO, string p_CONDICIONES, Nullable<decimal> p_USUARIO_FK, Nullable<decimal> p_TRAMO_FK)
        {
            var p_ID_CUPONParameter = p_ID_CUPON.HasValue ?
                new ObjectParameter("P_ID_CUPON", p_ID_CUPON) :
                new ObjectParameter("P_ID_CUPON", typeof(decimal));
    
            var p_PDFParameter = p_PDF != null ?
                new ObjectParameter("P_PDF", p_PDF) :
                new ObjectParameter("P_PDF", typeof(string));
    
            var p_TOPE_MAXIMOParameter = p_TOPE_MAXIMO.HasValue ?
                new ObjectParameter("P_TOPE_MAXIMO", p_TOPE_MAXIMO) :
                new ObjectParameter("P_TOPE_MAXIMO", typeof(decimal));
    
            var p_DESCUENTOParameter = p_DESCUENTO.HasValue ?
                new ObjectParameter("P_DESCUENTO", p_DESCUENTO) :
                new ObjectParameter("P_DESCUENTO", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_VENCIMIENTOParameter = p_VENCIMIENTO.HasValue ?
                new ObjectParameter("P_VENCIMIENTO", p_VENCIMIENTO) :
                new ObjectParameter("P_VENCIMIENTO", typeof(System.DateTime));
    
            var p_CONDICIONESParameter = p_CONDICIONES != null ?
                new ObjectParameter("P_CONDICIONES", p_CONDICIONES) :
                new ObjectParameter("P_CONDICIONES", typeof(string));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            var p_TRAMO_FKParameter = p_TRAMO_FK.HasValue ?
                new ObjectParameter("P_TRAMO_FK", p_TRAMO_FK) :
                new ObjectParameter("P_TRAMO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATECUPON", p_ID_CUPONParameter, p_PDFParameter, p_TOPE_MAXIMOParameter, p_DESCUENTOParameter, p_FECHAParameter, p_VENCIMIENTOParameter, p_CONDICIONESParameter, p_USUARIO_FKParameter, p_TRAMO_FKParameter);
        }
    
        public virtual int UPDATEEMPRESA(Nullable<decimal> p_ID_EMPRESA, string p_NOMBRE_EMPRESA, string p_RAZON_SOCIAL, string p_ESTADO, string p_RUT)
        {
            var p_ID_EMPRESAParameter = p_ID_EMPRESA.HasValue ?
                new ObjectParameter("P_ID_EMPRESA", p_ID_EMPRESA) :
                new ObjectParameter("P_ID_EMPRESA", typeof(decimal));
    
            var p_NOMBRE_EMPRESAParameter = p_NOMBRE_EMPRESA != null ?
                new ObjectParameter("P_NOMBRE_EMPRESA", p_NOMBRE_EMPRESA) :
                new ObjectParameter("P_NOMBRE_EMPRESA", typeof(string));
    
            var p_RAZON_SOCIALParameter = p_RAZON_SOCIAL != null ?
                new ObjectParameter("P_RAZON_SOCIAL", p_RAZON_SOCIAL) :
                new ObjectParameter("P_RAZON_SOCIAL", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEEMPRESA", p_ID_EMPRESAParameter, p_NOMBRE_EMPRESAParameter, p_RAZON_SOCIALParameter, p_ESTADOParameter, p_RUTParameter);
        }
    
        public virtual int UPDATEMAILLIST(Nullable<decimal> p_ID_MAILLIST, string p_SUSCRITO)
        {
            var p_ID_MAILLISTParameter = p_ID_MAILLIST.HasValue ?
                new ObjectParameter("P_ID_MAILLIST", p_ID_MAILLIST) :
                new ObjectParameter("P_ID_MAILLIST", typeof(decimal));
    
            var p_SUSCRITOParameter = p_SUSCRITO != null ?
                new ObjectParameter("P_SUSCRITO", p_SUSCRITO) :
                new ObjectParameter("P_SUSCRITO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMAILLIST", p_ID_MAILLISTParameter, p_SUSCRITOParameter);
        }
    
        public virtual int UPDATEOFERTA(Nullable<decimal> p_ID_OFERTA, Nullable<decimal> p_CANTIDAD_MINIMA, Nullable<decimal> p_CANTIDAD_MAXIMA, Nullable<decimal> p_PRECIO_NORMAL, Nullable<decimal> p_PRECIO_OFERTA, string p_IMAGEN, Nullable<System.DateTime> p_FECHA)
        {
            var p_ID_OFERTAParameter = p_ID_OFERTA.HasValue ?
                new ObjectParameter("P_ID_OFERTA", p_ID_OFERTA) :
                new ObjectParameter("P_ID_OFERTA", typeof(decimal));
    
            var p_CANTIDAD_MINIMAParameter = p_CANTIDAD_MINIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MINIMA", p_CANTIDAD_MINIMA) :
                new ObjectParameter("P_CANTIDAD_MINIMA", typeof(decimal));
    
            var p_CANTIDAD_MAXIMAParameter = p_CANTIDAD_MAXIMA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MAXIMA", p_CANTIDAD_MAXIMA) :
                new ObjectParameter("P_CANTIDAD_MAXIMA", typeof(decimal));
    
            var p_PRECIO_NORMALParameter = p_PRECIO_NORMAL.HasValue ?
                new ObjectParameter("P_PRECIO_NORMAL", p_PRECIO_NORMAL) :
                new ObjectParameter("P_PRECIO_NORMAL", typeof(decimal));
    
            var p_PRECIO_OFERTAParameter = p_PRECIO_OFERTA.HasValue ?
                new ObjectParameter("P_PRECIO_OFERTA", p_PRECIO_OFERTA) :
                new ObjectParameter("P_PRECIO_OFERTA", typeof(decimal));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEOFERTA", p_ID_OFERTAParameter, p_CANTIDAD_MINIMAParameter, p_CANTIDAD_MAXIMAParameter, p_PRECIO_NORMALParameter, p_PRECIO_OFERTAParameter, p_IMAGENParameter, p_FECHAParameter);
        }
    
        public virtual int UPDATEPRODUCTO(Nullable<decimal> p_ID_PRODUCTO, string p_NOMBRE_PRODUCTO, string p_DESCRIPCION, string p_COLOR, string p_PERECIBLE, string p_MARCA)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            var p_NOMBRE_PRODUCTOParameter = p_NOMBRE_PRODUCTO != null ?
                new ObjectParameter("P_NOMBRE_PRODUCTO", p_NOMBRE_PRODUCTO) :
                new ObjectParameter("P_NOMBRE_PRODUCTO", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_COLORParameter = p_COLOR != null ?
                new ObjectParameter("P_COLOR", p_COLOR) :
                new ObjectParameter("P_COLOR", typeof(string));
    
            var p_PERECIBLEParameter = p_PERECIBLE != null ?
                new ObjectParameter("P_PERECIBLE", p_PERECIBLE) :
                new ObjectParameter("P_PERECIBLE", typeof(string));
    
            var p_MARCAParameter = p_MARCA != null ?
                new ObjectParameter("P_MARCA", p_MARCA) :
                new ObjectParameter("P_MARCA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEPRODUCTO", p_ID_PRODUCTOParameter, p_NOMBRE_PRODUCTOParameter, p_DESCRIPCIONParameter, p_COLORParameter, p_PERECIBLEParameter, p_MARCAParameter);
        }
    
        public virtual int UPDATEPUNTOS(Nullable<decimal> p_ID_PUNTOS, Nullable<decimal> p_CANTIDAD, Nullable<decimal> p_USUARIO_FK)
        {
            var p_ID_PUNTOSParameter = p_ID_PUNTOS.HasValue ?
                new ObjectParameter("P_ID_PUNTOS", p_ID_PUNTOS) :
                new ObjectParameter("P_ID_PUNTOS", typeof(decimal));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_USUARIO_FKParameter = p_USUARIO_FK.HasValue ?
                new ObjectParameter("P_USUARIO_FK", p_USUARIO_FK) :
                new ObjectParameter("P_USUARIO_FK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEPUNTOS", p_ID_PUNTOSParameter, p_CANTIDADParameter, p_USUARIO_FKParameter);
        }
    
        public virtual int UPDATEROLUSUARIO(Nullable<decimal> p_ID_ROL_USUARIO, string p_NOMBRE)
        {
            var p_ID_ROL_USUARIOParameter = p_ID_ROL_USUARIO.HasValue ?
                new ObjectParameter("P_ID_ROL_USUARIO", p_ID_ROL_USUARIO) :
                new ObjectParameter("P_ID_ROL_USUARIO", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEROLUSUARIO", p_ID_ROL_USUARIOParameter, p_NOMBREParameter);
        }
    
        public virtual int UPDATERUBRO(Nullable<decimal> p_ID_RUBRO, string p_NOMBRE_RUBRO)
        {
            var p_ID_RUBROParameter = p_ID_RUBRO.HasValue ?
                new ObjectParameter("P_ID_RUBRO", p_ID_RUBRO) :
                new ObjectParameter("P_ID_RUBRO", typeof(decimal));
    
            var p_NOMBRE_RUBROParameter = p_NOMBRE_RUBRO != null ?
                new ObjectParameter("P_NOMBRE_RUBRO", p_NOMBRE_RUBRO) :
                new ObjectParameter("P_NOMBRE_RUBRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATERUBRO", p_ID_RUBROParameter, p_NOMBRE_RUBROParameter);
        }
    
        public virtual int UPDATETIENDA(Nullable<decimal> p_ID_TIENDA, string p_NOMBRE_TIENDA, string p_DIRECCION, string p_ESTADO)
        {
            var p_ID_TIENDAParameter = p_ID_TIENDA.HasValue ?
                new ObjectParameter("P_ID_TIENDA", p_ID_TIENDA) :
                new ObjectParameter("P_ID_TIENDA", typeof(decimal));
    
            var p_NOMBRE_TIENDAParameter = p_NOMBRE_TIENDA != null ?
                new ObjectParameter("P_NOMBRE_TIENDA", p_NOMBRE_TIENDA) :
                new ObjectParameter("P_NOMBRE_TIENDA", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATETIENDA", p_ID_TIENDAParameter, p_NOMBRE_TIENDAParameter, p_DIRECCIONParameter, p_ESTADOParameter);
        }
    
        public virtual int UPDATETRAMO(Nullable<decimal> p_ID_TRAMO, Nullable<decimal> p_MAXIMO, Nullable<decimal> p_MINIMO)
        {
            var p_ID_TRAMOParameter = p_ID_TRAMO.HasValue ?
                new ObjectParameter("P_ID_TRAMO", p_ID_TRAMO) :
                new ObjectParameter("P_ID_TRAMO", typeof(decimal));
    
            var p_MAXIMOParameter = p_MAXIMO.HasValue ?
                new ObjectParameter("P_MAXIMO", p_MAXIMO) :
                new ObjectParameter("P_MAXIMO", typeof(decimal));
    
            var p_MINIMOParameter = p_MINIMO.HasValue ?
                new ObjectParameter("P_MINIMO", p_MINIMO) :
                new ObjectParameter("P_MINIMO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATETRAMO", p_ID_TRAMOParameter, p_MAXIMOParameter, p_MINIMOParameter);
        }
    
        public virtual int UPDATEUSUARIO(Nullable<decimal> p_ID_USUARIO, string p_NOMBRES_USUARIO, string p_APELLIDO_PATERNO, string p_APELLIDO_MATERNO, string p_CORREO, string p_RUT, string p_ESTADO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            var p_NOMBRES_USUARIOParameter = p_NOMBRES_USUARIO != null ?
                new ObjectParameter("P_NOMBRES_USUARIO", p_NOMBRES_USUARIO) :
                new ObjectParameter("P_NOMBRES_USUARIO", typeof(string));
    
            var p_APELLIDO_PATERNOParameter = p_APELLIDO_PATERNO != null ?
                new ObjectParameter("P_APELLIDO_PATERNO", p_APELLIDO_PATERNO) :
                new ObjectParameter("P_APELLIDO_PATERNO", typeof(string));
    
            var p_APELLIDO_MATERNOParameter = p_APELLIDO_MATERNO != null ?
                new ObjectParameter("P_APELLIDO_MATERNO", p_APELLIDO_MATERNO) :
                new ObjectParameter("P_APELLIDO_MATERNO", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEUSUARIO", p_ID_USUARIOParameter, p_NOMBRES_USUARIOParameter, p_APELLIDO_PATERNOParameter, p_APELLIDO_MATERNOParameter, p_CORREOParameter, p_RUTParameter, p_ESTADOParameter);
        }
    
        public virtual int UPDATEVALORACION(Nullable<decimal> p_ID_VALORACION, Nullable<System.DateTime> p_FECHA, string p_IMAGEN, Nullable<decimal> p_CALIDAD, Nullable<decimal> p_ATENCION, Nullable<decimal> p_PRECIO, string p_COMENTARIO)
        {
            var p_ID_VALORACIONParameter = p_ID_VALORACION.HasValue ?
                new ObjectParameter("P_ID_VALORACION", p_ID_VALORACION) :
                new ObjectParameter("P_ID_VALORACION", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(string));
    
            var p_CALIDADParameter = p_CALIDAD.HasValue ?
                new ObjectParameter("P_CALIDAD", p_CALIDAD) :
                new ObjectParameter("P_CALIDAD", typeof(decimal));
    
            var p_ATENCIONParameter = p_ATENCION.HasValue ?
                new ObjectParameter("P_ATENCION", p_ATENCION) :
                new ObjectParameter("P_ATENCION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_COMENTARIOParameter = p_COMENTARIO != null ?
                new ObjectParameter("P_COMENTARIO", p_COMENTARIO) :
                new ObjectParameter("P_COMENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEVALORACION", p_ID_VALORACIONParameter, p_FECHAParameter, p_IMAGENParameter, p_CALIDADParameter, p_ATENCIONParameter, p_PRECIOParameter, p_COMENTARIOParameter);
        }
    }
}
