//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myOffers.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMO
    {
        public TRAMO()
        {
            this.CUPON = new HashSet<CUPON>();
        }
    
        public decimal ID_TRAMO { get; set; }
        public decimal MINIMO { get; set; }
        public decimal MAXIMO { get; set; }
    
        public virtual ICollection<CUPON> CUPON { get; set; }
    }
}
