//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miOffers.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.OFERTA = new HashSet<OFERTA>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string COLOR { get; set; }
        public string PERECIBLE { get; set; }
        public string MARCA { get; set; }
        public decimal RUBRO_FK { get; set; }
    
        public virtual ICollection<OFERTA> OFERTA { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
