//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miOffers.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTOS
    {
        public decimal ID_PUNTOS { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal USUARIO_FK { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
