//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miOffers.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORACION
    {
        public decimal ID_VALORACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string IMAGEN { get; set; }
        public decimal CALIDAD { get; set; }
        public decimal ATENCION { get; set; }
        public decimal PRECIO { get; set; }
        public string COMENTARIO { get; set; }
        public decimal OFERTA_FK { get; set; }
        public decimal USUARIO_FK { get; set; }
    
        public virtual OFERTA OFERTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
